### ISSUE TITLE
OBR Data corruption

### ISSUE THREAD

**Issue by ManuelLovell** [kamejosh/owlbear-hp-tracker#1]
There was an issue discovered in the Discord, something in the area of additional players joining and possibly other extensions (SIT) enabled.
A fix went out to prevent the data corruption on OBR, but it may have stopped your extension from working.  (Join the Discord for more details, as I honestly don't know a ton.)

**Comment by kamejosh** [comment]
thanks for letting me know, will check it out ASAP

**Comment by kamejosh** [comment]
has been fixed in #da8f985616bc8db958be645eea0be64d0371aba5

thanks again for notifying me @ManuelLovell
