### ISSUE TITLE
Move health bar to the top of tokens

### ISSUE THREAD

**Issue by SeamusFinlayson** [kamejosh/owlbear-hp-tracker#11]
I find the health bar usually overlaps the name plate at the bottom and was wondering if you would consider moving the health bar and labels to the top of the tokens.

**Comment by kamejosh** [comment]
I'm currently thinking about adding general options as suggested here: https://github.com/kamejosh/owlbear-hp-tracker/issues/9
Choosing the position of the HP bar would be one of the settings that'd go there

**Comment by kamejosh** [comment]
fixed with https://github.com/kamejosh/owlbear-hp-tracker/pull/13
you can now change the Y Position of the HP bar in the Global Settings via the offset
