### ISSUE TITLE
HP-Tracker Statblocks Rolling Twice

### ISSUE THREAD

**Issue by DoggoDoesaDash** [kamejosh/owlbear-hp-tracker#41]
Hi,

I've recently run into the problem of the dice prompts on statblocks rolling twice (without hitting advantage. When I use advantage it rolls with advantage twice (4 dice)). 

Let me know if there's anyway I can fix this issue.

thanks,

Jordan

**Comment by kamejosh** [comment]
Hmm it might be something to do with click propagation, I will look into it

**Comment by kamejosh** [comment]
Was because HP Tracker and dddice extension were both active and so the dice rolls were rendered by both extensions. Disabling one renderer solved the problem.
