### ISSUE TITLE
All Objects Wiped Out of Scene

### ISSUE THREAD

**Issue by peckaar** [kamejosh/owlbear-hp-tracker#5]
I had all objects removed from a scene unexpectedly while using this extension. I am not sure if there’s something I’m doing or have loaded - I didn’t notice a common trigger. It happened on two difference scenes inside one room. Needless to say I’m hesitant to try it again. I’m using Firefox browser on Windows. Thoughts?

**Comment by peckaar** [comment]
Thinking about it I think the trigger was that I added some tokens by clicking Active and they weren't showing up in the left panel so I refreshed the browser. It came back without any objects even after logging out of the profile and back in.

**Comment by kamejosh** [comment]
Hey,
can you tell me a bit more about the other extensions you're using? HP Tracker currently has only 2 calls to `delete` and only handles TextItems that contain a certain metadata key. This metadata key is only added to TextItems that are created by the Extension. So I'm really not sure what could cause other Items to be deleted. 

One thing that might restore your Scene could be resetting the cache (I think CTRL + F5 on Windows). Maybe there is an old version of an extension causing you troubles.

I'm sorry that I cannot be more helpfull, I tried recreating the problem with new scenes, old scenes and scenes that were created without the extension installed and didn't encounter the error 😞

**Comment by kamejosh** [comment]
it might be fixed now, if you encounter this problem again please let me know
