### ISSUE TITLE
Feature Request: Show Players Fuzzy Status

### ISSUE THREAD

**Issue by cgbeutler** [kamejosh/owlbear-hp-tracker#9]
At most tables I've played at and in my own running, we tend to devolve into using 5-levels of hp info that are something like untouched, damaged, middling, "looking sad," and downed/dead.
It'd be nice to be able to have the health bar show up, but round to 4ths. That way players get a basic sense of where things are at, but don't know _exactly_ what the remaining health is. I know this style isn't everyone's cup of tea, but it'd be a nice option for DMs like me, I think. (If this doesn't get any upvotes, then I totally get never adding the feature. Keep up the good work!)

**Comment by kamejosh** [comment]
I think if I find an intuitive option to set it in the interface it should be no problem to implement. Will have to think about it though, and I am currently working on other features (ordering entries only for the GM, initiative field, basic character sheets). So it will probably take a few weeks.

**Comment by cgbeutler** [comment]
I think I'd prefer the "style" options to just be global at the top/bottom of the health window. All the visibility could then still be columns, but with a show/hide all, too.

**Comment by kamejosh** [comment]
I think I will introduce global settings, like style of the HP Bar, but I really like and need the granular settings for my own games 😁
